# Data transformation
  Our data was provided as two separate csv’s, one for the Billboard Top 100 rankings, and the other for the Spotify audio features. The kind folks at TidyTuesday already created a song_id column in both csv’s, which was the concatenation of the song name and the artist. We found that using Python to do our data merging and transformation to be the most seamless. The Jupyter Notebook with our code can be found [here](https://github.com/alexandriaGuo/billboard-top-100/blob/main/data_clean.ipynb). 

  To transform the Billboard data, we noticed that there were only NAs in the previous week position column, and that it corresponded to when the song first appeared on the charts. Instead of keeping them as nulls, to be slightly more descriptive, we null-filled those instances with “debut”.

  To merge the two datasets, I left-joined on the Billboard dataset, in order to maintain all of our Billboard data. During the initial join, we noticed the data was growing in size, which was due to the duplicate song instances in the Spotify dataset. The data was de-duplicated based on the song_id. Another thing to note is that we did not separate out artists that were featured on a song or if there were multiple artists listed on a song. We treated each combination of artists as a unique artist. Another issue with featured artists is that often the Spotify data for that song would be missing. We believe that it is due to Spotify listing the song/artist in a different way than Billboard, and because we are joining on Artist and Song as our id, this could have caused issues with looking up Spotify data. As a result the Spotify data (genre, musicality features, etc.) for many songs with features is missing.

  After merging, we noticed that the Spotify genre feature was actually a list of genres that Spotify associated with the song. Additionally, there were hundreds of unique genres since Spotify is very detailed in their description of pop (dance pop, post-teen pop, space age pop, brill building pop, pop rap to name a few). To deal with this, we decided on distilling the list to a single representative genre. We went through the list of genres, and matched on a common list of genres such as rap, country, pop, k-pop, jazz, and more. If the song did not have any of those genres, it was assigned other. Additionally, since many songs had pop as a genre, we decided to match on any of the other genres first, before resorting to pop. As a result, this might deflate the number of songs labeled as pop. Ideally, we would have been able to count all of the instances of each genre, and could be a worthwhile future improvement. 

  To make our plots generally more readable, we decided to filter down our dataset to songs after the 2000s, as they are more recent and relevant. The exceptions are the plots that focus on a meta-analysis by each decade, as well as for our interactive plot; in order to make the dataset a manageable size to be shared online, we decided to only use songs between 2011-2021.
