# Conclusion

Through this brief exploration of popular music, we have found a number of interesting insights from the data, namely that people surprisingly have some consistent tastes in their favorite music. Whether that is certain musical features remaining as staples in the composition of popular songs through the decades, genres such as rock and pop consistently making up a portion of the top songs of any decade, or even the same few artists and songs dominating the top positions on the Billboard charts over the last 20 years, we have learned that there are some elements of music that can stand the test of time, even as trends come and go.

While this initial exploration has offered some interesting discoveries, there are some limitations in the data provided that could be refined and provide an interesting direction for future work. For example, handling missing song features and genres to create a more complete dataset, such as by re-querying the Spotify API, could unearth additional trends. For plots that used genre, it could be interesting to try different methods of genre assignment in the initial data cleaning to see if it could provide new insights that we might have missed. It would also be interesting to cross-reference another database for assigning a single genre to a song since Spotify assigns so many sub-genres. Finally, with so many dimensions to our dataset, there are definitely many other questions that are left unanswered with our exploration. If we had the time, we would have liked to explore derived metrics such as changes in position on the charts and the “velocity” of songs moving between positions on the Top 100 charts. 

In addition to future data analysis directions, putting together this project taught us some valuable lessons. Primarily, we’ve learned to make sure to work piece by piece, and that changes to the Bookdown work incrementally, instead of trying to merge everything all at once. The same lesson can also be applied to creating the interactive plot. We also learned the value of getting started early, and continuing to explore the data even after an initial survey. This project has also taught us to use a gut-check to make sure that plots make sense logically, and to deep dive into the data when it doesn’t pass (using Excel is a great way to verify work done in R or d3). It also helped us to use the approach of first clearly formulating the question, then spending some time to brainstorm and sketch out different plots that could help provide answers, before diving straight into making the plot in R. Overall, our team had a lot of fun exploring and analyzing the Billboard Top 100 and the Spotify audio features datasets to get a different perspective of the music we loved listening to, and look forward to future analyses as well. 
