---
title: "final_proj_julia"
author: "Julia Wang"
date: "11/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(ggplot2)
library(lubridate)
```

## Ingest the data:
We did a bit of data cleaning and wrangling using python, and this is our final cleaned version of the data set prepped for our data exploration and visualization.
```{r load data}
data <- read_csv("~/Desktop/Columbia/Fall2021/STAT5702/billboard-top-100/billboard_spotify_cleaned_final.csv")

data$week_id = as.Date(data$week_id, format = '%m/%d/%Y') 
glimpse(data)
```

```{r data cleaning}
data_2000 <- data %>% filter(week_id >= as.Date("2000-1-1"))

```

```{r top 50 songs by # of weeks on charts}
top_song <- data_2000 %>% 
  group_by(song, performer) %>% 
  slice(which.max(weeks_on_chart)) %>% 
  arrange(desc(weeks_on_chart)) %>% 
  head(50)


ggplot(top_song, aes(x = weeks_on_chart, y = reorder(song, weeks_on_chart), color=spotify_genre_clean)) +
  geom_point()


```
```{r top song by # of weeks at #1}
top_song_1 <- data_2000 %>% 
  group_by(song) %>% 
  filter(week_position == 1) %>% 
  add_count() %>% 
  slice(which.max(week_id)) %>% 
  arrange(desc(n)) %>% 
  head(50)

ggplot(top_song_1, aes(x = n, y = reorder(song, n), color = spotify_genre_clean)) +
  geom_point()


```

```{r top artists by number of songs on chart}
top_artists <- data_2000 %>% 
  group_by(performer, song) %>% 
  slice(which.max(week_id)) %>% 
  group_by(performer) %>% 
  count() %>% 
  arrange(desc(n)) %>% 
  head(50)

ggplot(top_artists, aes(x = n, y = reorder(performer, n))) +
  geom_point()
```

```{r top artists by number of #1 songs on chart}
top_artists_1 <- data_2000 %>% 
  group_by(performer, song) %>% 
  filter(week_position==1) %>% 
  slice(which.max(week_id)) %>% 
  group_by(performer) %>% 
  count() %>% 
  arrange(desc(n)) %>% 
  head(35)

ggplot(top_artists_1, aes(x = n, y = reorder(performer, n))) +
  geom_point()
```